#include <iostream>

#include "memory.hpp"
// generated by xxd -i ... 
#include "48rom.h"
#include "diagrom.h"
#include "diagrom2.h"

Memory::Memory() {
    // Initialize all memory to zero
    for (int i = 0; i < 65536; i++) {
        memory[i] = 0x00;
    }
    canWriteRom = false;
}

uint8_t Memory::ReadByte(uint16_t address) {
    if(address > 0xfff0) {
        printf("RB %x %x\n", address, memory[address]);
    }
    return memory[address];
}

void Memory::WriteByte(uint16_t address, uint8_t value) {
    if(address < 0x4000 && canWriteRom == false) {
        printf("Ignoring attempt to write byte to ROM %x %x\n",address,value);
        return;
    }
     if(address > 0xfff0) {
        printf("WB %x %x\n", address, value);
    }
    memory[address] = value;
    if(address > 0xfff0) {
        printf("WB2 %x %x\n", address, memory[address]);
    }
}

uint16_t Memory::ReadWord(uint16_t address) {
    // Read word in little-endian format (least significant byte first)
    uint8_t low = memory[address];
    uint8_t high = memory[address + 1];
    if(address > 0xfff0) {
        printf("RW %x %x%x\n", address, memory[address],memory[address+1]);
    }
    return (static_cast<uint16_t>(high) << 8) | static_cast<uint16_t>(low);
}

void Memory::WriteWord(uint16_t address, uint16_t value) {
    if(address < 0x4000 && canWriteRom == false) {
        printf("Ignoring attempt to write word to ROM %x %x\n",address,value);
        return;
    }
    if(address > 0xfff0) {
        printf("WW %x %x\n", address, value);
    }
    // Write word in little-endian format (least significant byte first)
    memory[address] = static_cast<uint8_t>(value & 0xFF);
    memory[address + 1] = static_cast<uint8_t>((value >> 8) & 0xFF);
}

void Memory::Read48(void) {
    canWriteRom = true;
for (unsigned int i = 0; i < __48_rom_len; i++) {
        WriteByte(i,__48_rom[i]);
    }
    canWriteRom = false;
}

void Memory::ReadDiag(void) {
    canWriteRom = true;
for (unsigned int i = 0; i < testrom_bin_len; i++) {
        WriteByte(i,testrom_bin[i]);
    }
    canWriteRom = false;
}

void Memory::ReadDiag2(void) {
    canWriteRom = true;
for (unsigned int i = 0; i < DiagROMv_173_len; i++) {
        WriteByte(i,DiagROMv_173[i]);
    }
    canWriteRom = false;
}