#include <iostream>

#include "memory.hpp"
// generated by xxd -i ...
#include "48rom.h"
#include "diagrom.h"
#include "diagrom2.h"

Memory::Memory()
{
    // Initialize all memory to zero
    for (int i = 0; i < 65536; i++)
    {
        memory[i] = 0x00;
    }
    canWriteRom = false;
}

uint8_t Memory::ReadByte(uint16_t address)
{
    return memory[address];
}

void Memory::WriteByte(uint16_t address, uint8_t value)
{
    if (address < 0x4000 && canWriteRom == false)
    {
        // printf("Ignoring attempt to write byte to ROM %x %x\n",address,value);
        return;
    }
    memory[address] = value;
}

void Memory::Read48(void)
{
    canWriteRom = true;
    for (unsigned int i = 0; i < __48_rom_len; i++)
    {
        WriteByte(i, __48_rom[i]);
    }
    canWriteRom = false;
}

void Memory::ReadDiag(void)
{
    canWriteRom = true;
    for (unsigned int i = 0; i < testrom_bin_len; i++)
    {
        WriteByte(i, testrom_bin[i]);
    }
    canWriteRom = false;
}

void Memory::ReadDiag2(void)
{
    canWriteRom = true;
    for (unsigned int i = 0; i < DiagROMv_173_len; i++)
    {
        WriteByte(i, DiagROMv_173[i]);
    }
    canWriteRom = false;
}
